### ISSUE TITLE
Error! Unexpected token occurs when some lib in dependencies list 

### ISSUE THREAD

**Issue by ngloom** [zeit/pkg#317] opened 2018-01-03 14:49 UTC
adding     ` "normalize.css": "7.0.0" `
in dependencies in the example's  package.json and then run `pkg .`
will get a  `> Error! Unexpected token (12:5) `
pkg version pkg@4.2.5
my project need this dependency , is there any solution?

**Comment by motin** [comment] 2018-10-18 19:08
I have the same question/issue, but with another library:
```
> Error! Unexpected token (14:0)
  /Users/motin/Dev/Projects/sq/sq-project/tools/clerk-cli/node_modules/pouchdb-fauxton/www/index.html
```

**Comment by motin** [comment] 2018-10-18 19:12
This seems to be a duplicate of https://github.com/zeit/pkg/issues/75

**Comment by grushetsky** [comment] 2018-10-26 02:10
I can confirm the same issue with `normalize.css` version 8.0.0 and `pkg` version 4.3.4:

```
Error! Unexpected token, expected ";" (11:5)
…/node_modules/normalize.css/normalize.css
```

**Comment by arpitprod** [comment] 2019-12-12 08:03
@grushetsky any solution? I'm also facing same error

**Comment by grushetsky** [comment] 2019-12-12 11:05
@arpitprod, removing _/node_modules/normalize.css_ right after the build and before using `pkg` helped to avoid this issue:

```json
{
  "scripts": {
    "dist": "pkg …",
    "build": "…",
    "predist": "yarn build && rm -rf node_modules/normalize.css",
    "postdist": "yarn install"
  }
}
```

**Closed** 2019-12-14 23:18 UTC
